version: "3.8"
services:
  bankdb:
    image: postgres:16
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: supersecretbank
      POSTGRES_DB: bankapp
    ports:
      - "4321:5432"
    volumes:
      - bankdb_data:/var/lib/postgresql/data

  agentdb:
    image: postgres:16
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: supersecretagent
      POSTGRES_DB: agentapp
    ports:
      - "6543:5432"
    volumes:
      - agentdb_data:/var/lib/postgresql/data


volumes:
  bankdb_data:
  agentdb_data: